#!/usr/bin/env python3
"""
Documentation structure generator (v2) for the Ibn Hayan Healthcare Operating System.

This is the upgraded version that:
  - Adds docs/03_DOMAIN/        (8 new files)
  - Adds docs/08_INTEGRATIONS/  (8 new files)
  - Adds docs/09_SECURITY/COMPLIANCE/  (6 new files in subfolder)
  - Adds docs/12_ADR/           (6 ADR files using ADR template)
  - Renumbers existing folders to maintain sequential 00-14 with no gaps
  - Confirms PRODUCT_BIBLE naming (no PROJECT_BIBLE anywhere)
  - Validates the final structure

Final structure: 15 top-level folders, 121 markdown files total.
"""

from pathlib import Path
from datetime import date
import shutil

BASE = Path("/home/z/my-project/download/docs")
TODAY = date.today().isoformat()

# -------------------------------------------------------------------------
# Standard documentation template (used by most files)
# -------------------------------------------------------------------------
TEMPLATE = """# Ibn Hayan Healthcare Operating System
## {title}

> **Document Purpose:** {description}
>
> **Status:** Draft · **Version:** 0.1.0 · **Last Updated:** {today}
>
> This document is part of the official Ibn Hayan Healthcare Operating System
> documentation framework and serves as the authoritative reference for its
> respective domain. It is intended for the entire product, engineering,
> design, clinical, and operations teams.

---

## Table of Contents

{toc}

---

{sections}
"""

# -------------------------------------------------------------------------
# ADR-specific template (Architectural Decision Records)
# -------------------------------------------------------------------------
ADR_TEMPLATE = """# ADR-{number}: {title}
## Ibn Hayan Healthcare Operating System — Architectural Decision Record

> **Document Purpose:** {description}
>
> **Status:** Draft · **ADR Number:** {number} · **Last Updated:** {today}
>
> This Architectural Decision Record (ADR) documents a significant architectural
> decision made for the Ibn Hayan Healthcare Operating System. ADRs are
> immutable historical records — once a decision is superseded, a new ADR
> is created rather than editing this one.

---

## Table of Contents

1. Decision
2. Context
3. Alternatives
4. Consequences
5. Status
6. Future Notes

---

## 1. Decision

## 2. Context

## 3. Alternatives

## 4. Consequences

## 5. Status

## 6. Future Notes
"""


# Each entry: (relative_path, title, description, [section_headings])
FILES = [

    # ====================================================================
    # 00_PROJECT
    # ====================================================================
    ("00_PROJECT/PRODUCT_BIBLE.md",
     "Product Bible",
     "The authoritative single source of truth for the entire Ibn Hayan Healthcare Operating System — defining what we build, why it exists, who it serves, and how success is measured.",
     ["Executive Summary",
      "Product Definition",
      "Core Value Proposition",
      "Target Market & Personas",
      "Key Differentiators",
      "Product Principles",
      "Strategic Objectives",
      "Success Metrics & KPIs",
      "Stakeholder Map",
      "Competitive Landscape",
      "Product Boundaries",
      "Glossary of Terms",
      "Related Documents",
      "Revision History"]),

    ("00_PROJECT/PROJECT_VISION.md",
     "Project Vision",
     "The long-term vision and directional north star for the Ibn Hayan Healthcare Operating System across 5-year and 10-year horizons.",
     ["Vision Statement",
      "Mission",
      "Core Values",
      "Strategic Pillars",
      "5-Year Vision",
      "10-Year Vision",
      "North Star Metrics",
      "Strategic Themes",
      "Vision Alignment with Stakeholders",
      "Vision Evolution History",
      "Related Documents"]),

    ("00_PROJECT/PROJECT_SCOPE.md",
     "Project Scope",
     "Defines what is in-scope and out-of-scope for the Ibn Hayan Healthcare Operating System across phases, including assumptions, dependencies, and scope-change governance.",
     ["Scope Definition",
      "In-Scope Modules",
      "Out-of-Scope Items",
      "Phase 1 Scope (MVP)",
      "Phase 2 Scope (Growth)",
      "Phase 3 Scope (Scale)",
      "Future Scope Considerations",
      "Assumptions",
      "Dependencies",
      "Constraints",
      "Scope Change Process",
      "Scope Governance",
      "Related Documents"]),

    ("00_PROJECT/PRODUCT_ROADMAP.md",
     "Product Roadmap",
     "The phased delivery roadmap with quarterly milestones, release themes, feature prioritization, and dependency mapping across the product lifecycle.",
     ["Roadmap Overview",
      "Roadmap Methodology",
      "Quarterly Milestones",
      "Release Themes",
      "Feature Prioritization Framework",
      "Release Cadence",
      "Dependency Map",
      "Risk Considerations",
      "Resource Allocation",
      "Roadmap Communication",
      "Roadmap Archive",
      "Related Documents"]),

    ("00_PROJECT/BUSINESS_MODEL.md",
     "Business Model",
     "How the Ibn Hayan Healthcare Operating System creates, delivers, and captures value — covering revenue streams, pricing, customer segments, and cost structure.",
     ["Business Model Canvas",
      "Value Propositions",
      "Customer Segments",
      "Revenue Streams",
      "Pricing Strategy",
      "Distribution Channels",
      "Customer Relationships",
      "Key Activities",
      "Key Resources",
      "Key Partnerships",
      "Cost Structure",
      "Unit Economics",
      "Financial Projections",
      "Related Documents"]),

    ("00_PROJECT/CHANGELOG.md",
     "Changelog",
     "Chronological record of all notable changes to the Ibn Hayan Healthcare Operating System across product, documentation, and infrastructure.",
     ["Versioning Scheme",
      "Release Categories",
      "Current Version",
      "Release History",
      "Upcoming Releases",
      "Deprecation Notices",
      "Breaking Changes Archive",
      "Migration Notes",
      "Related Documents"]),

    # ====================================================================
    # 01_ARCHITECTURE
    # ====================================================================
    ("01_ARCHITECTURE/SYSTEM_ARCHITECTURE.md",
     "System Architecture",
     "The highest-level architectural view of the Ibn Hayan Healthcare Operating System — covering components, deployment topology, network, data flow, and non-functional requirements.",
     ["Architecture Overview",
      "Architectural Style",
      "Architectural Principles",
      "High-Level Components",
      "System Context Diagram",
      "Container View",
      "Deployment View",
      "Network Architecture",
      "Data Flow Architecture",
      "Integration Architecture",
      "Multi-Tenancy Architecture",
      "Non-Functional Requirements",
      "Architectural Decision Records (ADRs)",
      "Architecture Review Process",
      "Related Documents"]),

    ("01_ARCHITECTURE/SOFTWARE_ARCHITECTURE.md",
     "Software Architecture",
     "The internal software architecture — patterns, layering, service decomposition, dependency management, and cross-cutting concerns.",
     ["Software Architecture Overview",
      "Architectural Patterns",
      "Layered Architecture",
      "Service Architecture",
      "Module Decomposition",
      "Dependency Management",
      "Cross-Cutting Concerns",
      "Design Principles (SOLID, DRY, KISS)",
      "Technology Stack",
      "Framework Selection",
      "Architectural Trade-offs",
      "Technical Debt Management",
      "Related Documents"]),

    ("01_ARCHITECTURE/MODULE_ARCHITECTURE.md",
     "Module Architecture",
     "The module-level architectural design — boundaries, contracts, dependencies, lifecycle, versioning, and extension points for all system modules.",
     ["Module Architecture Overview",
      "Module Catalog",
      "Module Boundaries",
      "Module Contracts",
      "Module Dependencies",
      "Module Lifecycle",
      "Module Communication Patterns",
      "Module Versioning",
      "Module Extension Points",
      "Module Configuration Surface",
      "Module Isolation Strategy",
      "Module Testing Strategy",
      "Related Documents"]),

    ("01_ARCHITECTURE/CONFIGURATION_ARCHITECTURE.md",
     "Configuration Architecture",
     "How configuration is structured, layered, validated, and applied across tenants, modules, environments, and feature flags.",
     ["Configuration Overview",
      "Configuration Layers",
      "Tenant Configuration",
      "Module Configuration",
      "Feature Flags",
      "Configuration Storage",
      "Configuration Validation",
      "Configuration Lifecycle",
      "Environment-Specific Configuration",
      "Configuration Security",
      "Configuration Hot-Reload",
      "Configuration Audit Trail",
      "Related Documents"]),

    ("01_ARCHITECTURE/FOLDER_STRUCTURE.md",
     "Folder Structure",
     "The canonical repository layout for the Ibn Hayan Healthcare Operating System — top-level directories, source organization, naming conventions, and asset management.",
     ["Repository Layout Overview",
      "Top-Level Directories",
      "Source Code Organization",
      "Module Structure",
      "Test Organization",
      "Documentation Layout",
      "Asset Management",
      "Configuration Files",
      "Build Artifacts",
      "Naming Conventions",
      "Monorepo vs Polyrepo Strategy",
      "Related Documents"]),

    ("01_ARCHITECTURE/CODING_STANDARDS.md",
     "Coding Standards",
     "The mandatory coding standards governing all source code in the Ibn Hayan Healthcare Operating System — style, naming, structure, error handling, and review.",
     ["General Principles",
      "Language-Specific Standards",
      "Naming Conventions",
      "File Organization",
      "Code Formatting Rules",
      "Comment & Documentation Standards",
      "Error Handling Standards",
      "Testing Standards",
      "Code Review Process",
      "Refactoring Guidelines",
      "Linting & Static Analysis",
      "Code Quality Metrics",
      "Related Documents"]),

    # ====================================================================
    # 02_PRODUCT
    # ====================================================================
    ("02_PRODUCT/MODULES.md",
     "Modules",
     "The complete catalog of all product modules — core, specialty, add-on, deprecated, and future — with lifecycle status and dependencies.",
     ["Module Inventory Overview",
      "Core Modules",
      "Specialty Modules",
      "Add-on Modules",
      "Module Lifecycle Statuses",
      "Module Catalog Table",
      "Module Dependencies Matrix",
      "Module Maturity Levels",
      "Deprecated Modules",
      "Future Modules Pipeline",
      "Module Selection Guide",
      "Related Documents"]),

    ("02_PRODUCT/USER_ROLES.md",
     "User Roles",
     "All defined user roles across clinical, administrative, financial, technical, patient, and external categories with role hierarchy and definitions.",
     ["Role Overview",
      "Role Hierarchy",
      "Clinical Roles",
      "Administrative Roles",
      "Financial Roles",
      "Technical Roles",
      "Patient & Portal Roles",
      "External & Partner Roles",
      "Role Definitions",
      "Role Matrix",
      "Role Assignment Workflow",
      "Custom Role Support",
      "Related Documents"]),

    ("02_PRODUCT/PERMISSIONS.md",
     "Permissions",
     "The permission model governing access to resources, actions, and fields across the entire Ibn Hayan Healthcare Operating System.",
     ["Permission Overview",
      "Permission Model",
      "Permission Categories",
      "Permission Granularity",
      "Role-Permission Mapping",
      "Resource-Level Permissions",
      "Action-Level Permissions",
      "Field-Level Permissions",
      "Permission Inheritance",
      "Permission Management",
      "Permission Evaluation",
      "Permission Caching",
      "Related Documents"]),

    ("02_PRODUCT/WORKFLOWS.md",
     "Workflows",
     "The end-to-end clinical, administrative, and financial workflows that the Ibn Hayan Healthcare Operating System supports out of the box.",
     ["Workflow Overview",
      "Patient Journey Workflow",
      "Appointment Workflow",
      "Clinical Encounter Workflow",
      "Billing & Payment Workflow",
      "Inventory Workflow",
      "Laboratory Workflow",
      "Pharmacy Workflow",
      "Reporting Workflow",
      "Notification Workflow",
      "Custom Workflow Engine",
      "Workflow Configuration",
      "Related Documents"]),

    ("02_PRODUCT/FEATURES.md",
     "Features",
     "The complete feature catalog with status, maturity, dependencies, configuration options, and edition availability.",
     ["Feature Catalog Overview",
      "Core Features",
      "Specialty Features",
      "Premium Features",
      "Feature Status Definitions",
      "Feature Deprecation Policy",
      "Feature Prioritization",
      "Feature Dependencies",
      "Feature Configuration",
      "Feature Discovery & Adoption",
      "Feature Roadmap Alignment",
      "Related Documents"]),

    ("02_PRODUCT/EDITIONS.md",
     "Editions",
     "Product editions and pricing tiers — Starter, Professional, Enterprise, Hospital — with feature comparison and upgrade paths.",
     ["Edition Overview",
      "Edition Strategy",
      "Starter Edition",
      "Professional Edition",
      "Enterprise Edition",
      "Hospital Edition",
      "Edition Comparison Matrix",
      "Edition Upgrade Path",
      "Edition Pricing Model",
      "Edition Limitations & Quotas",
      "Edition Customization",
      "Related Documents"]),

    ("02_PRODUCT/CLINIC_TYPES.md",
     "Clinic Types",
     "All supported medical facility types — clinics, medical centers, labs, radiology, hospitals, cosmetic centers — with configuration and module mapping.",
     ["Clinic Type Overview",
      "Clinic Type Catalog",
      "Single-Specialty Facilities",
      "Multi-Specialty Facilities",
      "Clinic Type Configuration",
      "Clinic Type Module Mapping",
      "Clinic Type Workflow Mapping",
      "Clinic Type Customization",
      "Clinic Type Onboarding",
      "Clinic Type Templates",
      "Future Clinic Types",
      "Related Documents"]),

    # ====================================================================
    # 03_DOMAIN (NEW)
    # ====================================================================
    ("03_DOMAIN/BUSINESS_RULES.md",
     "Business Rules",
     "The canonical catalog of all business rules governing the Ibn Hayan Healthcare Operating System — definitions, ownership, evaluation, conflicts, and lifecycle.",
     ["Business Rules Overview",
      "Rule Definition Standard",
      "Rule Catalog",
      "Clinical Business Rules",
      "Financial Business Rules",
      "Administrative Business Rules",
      "Regulatory Business Rules",
      "Rule Ownership & Governance",
      "Rule Evaluation Engine",
      "Rule Conflict Resolution",
      "Rule Versioning & Lifecycle",
      "Rule Testing & Validation",
      "Rule Documentation Standards",
      "Related Documents"]),

    ("03_DOMAIN/CLINICAL_WORKFLOWS.md",
     "Clinical Workflows",
     "The canonical clinical workflow definitions across all specialties — patient encounters, clinical pathways, care plans, and decision trees.",
     ["Clinical Workflows Overview",
      "Workflow Modeling Standard",
      "Patient Encounter Workflow",
      "Clinical Pathways",
      "Care Plan Workflows",
      "Clinical Decision Trees",
      "Specialty-Specific Workflows",
      "Emergency & Urgent Care Workflows",
      "Chronic Disease Management Workflows",
      "Workflow Customization Framework",
      "Workflow Validation & Compliance",
      "Workflow Analytics",
      "Related Documents"]),

    ("03_DOMAIN/TERMINOLOGY.md",
     "Terminology",
     "The controlled medical vocabulary and terminology standards adopted across the Ibn Hayan Healthcare Operating System — SNOMED CT, LOINC, ICD-10/11, RxNorm, and local terms.",
     ["Terminology Overview",
      "Terminology Standards (SNOMED CT, LOINC, ICD-10/11, RxNorm)",
      "Local Terminology Extensions",
      "Terminology Mapping",
      "Code System Governance",
      "Terminology Binding to Data Models",
      "Multi-Language Terminology Support",
      "Arabic Terminology Considerations",
      "Terminology Search & Lookup",
      "Terminology Versioning",
      "Terminology Maintenance Process",
      "Related Documents"]),

    ("03_DOMAIN/ENUMS.md",
     "Enumerations",
     "The complete catalog of all enumerated types used across the Ibn Hayan Healthcare Operating System — values, codes, labels, and localization.",
     ["Enumerations Overview",
      "Enum Definition Standard",
      "Patient Enums",
      "Clinical Enums",
      "Financial Enums",
      "Inventory Enums",
      "Workflow & Status Enums",
      "System Enums",
      "Enum Localization",
      "Enum Extension Policy",
      "Enum Deprecation Policy",
      "Enum Registry",
      "Related Documents"]),

    ("03_DOMAIN/STATUS_CODES.md",
     "Status Codes",
     "The complete catalog of status codes used across entities, workflows, transactions, and integrations — semantics, transitions, and lifecycle.",
     ["Status Codes Overview",
      "Status Code Standard",
      "Patient Status Codes",
      "Appointment Status Codes",
      "Encounter & Visit Status Codes",
      "Order & Result Status Codes",
      "Billing & Payment Status Codes",
      "Inventory Status Codes",
      "Subscription Status Codes",
      "Status Transition Maps",
      "Status Code Localization",
      "Status Code Audit",
      "Related Documents"]),

    ("03_DOMAIN/CALCULATIONS.md",
     "Calculations",
     "The canonical calculation definitions across the platform — billing, payroll, taxes, discounts, medical scores, dosages, and analytics.",
     ["Calculations Overview",
      "Calculation Definition Standard",
      "Billing Calculations",
      "Payroll & Compensation Calculations",
      "Tax Calculations",
      "Discount & Promotion Calculations",
      "Medical Score Calculations",
      "Dosage Calculations",
      "Analytics & KPI Calculations",
      "Calculation Engine Architecture",
      "Calculation Testing & Validation",
      "Calculation Audit Trail",
      "Related Documents"]),

    ("03_DOMAIN/CONFIGURATION.md",
     "Domain Configuration",
     "The domain-level configuration catalog — what can be configured per tenant, per specialty, per module, with defaults, validation, and inheritance.",
     ["Domain Configuration Overview",
      "Configuration Schema Standard",
      "Tenant-Level Configuration",
      "Specialty-Level Configuration",
      "Module-Level Configuration",
      "Workflow Configuration",
      "Form & Template Configuration",
      "Notification Configuration",
      "Integration Configuration",
      "Configuration Defaults & Inheritance",
      "Configuration Validation Rules",
      "Configuration Change Management",
      "Related Documents"]),

    ("03_DOMAIN/FEATURE_FLAGS.md",
     "Feature Flags",
     "The feature flag framework — taxonomy, lifecycle, evaluation, rollout strategy, targeting, kill switches, and audit trail.",
     ["Feature Flags Overview",
      "Flag Taxonomy",
      "Flag Lifecycle",
      "Flag Evaluation Engine",
      "Rollout Strategies",
      "Targeting Rules",
      "Kill Switches & Emergency Flags",
      "Flag Governance",
      "Flag Audit Trail",
      "Flag Testing",
      "Flag Deprecation",
      "Related Documents"]),

    # ====================================================================
    # 04_DATABASE (renumbered from 03)
    # ====================================================================
    ("04_DATABASE/DATABASE_DESIGN.md",
     "Database Design",
     "The overall database design strategy — engine selection, multi-tenancy, partitioning, replication, backup, performance, and high availability.",
     ["Database Overview",
      "Database Strategy",
      "Database Engine Selection",
      "Multi-Tenancy Strategy",
      "Data Partitioning",
      "Sharding Strategy",
      "Replication Strategy",
      "Backup Strategy",
      "Performance Strategy",
      "High Availability & Failover",
      "Disaster Recovery Strategy",
      "Database Security",
      "Related Documents"]),

    ("04_DATABASE/TABLES.md",
     "Tables",
     "The complete catalog of database tables organized by domain — core, clinical, financial, inventory, audit, configuration, junction, and lookup.",
     ["Table Catalog Overview",
      "Core Tables",
      "Clinical Tables",
      "Financial Tables",
      "Inventory Tables",
      "Audit Tables",
      "Configuration Tables",
      "Junction Tables",
      "Lookup Tables",
      "Table Naming Conventions",
      "Table Schema Versioning",
      "Related Documents"]),

    ("04_DATABASE/RELATIONSHIPS.md",
     "Relationships",
     "All entity relationships in the Ibn Hayan Healthcare Operating System database — cardinalities, foreign keys, cascade rules, soft deletes, and referential integrity.",
     ["Relationship Overview",
      "Entity Relationship Diagrams",
      "One-to-One Relationships",
      "One-to-Many Relationships",
      "Many-to-Many Relationships",
      "Foreign Key Policies",
      "Cascade Rules",
      "Soft Delete Strategy",
      "Referential Integrity Enforcement",
      "Relationship Patterns",
      "Orphan Record Handling",
      "Related Documents"]),

    ("04_DATABASE/DATA_MODELS.md",
     "Data Models",
     "The logical data models for each major domain — patient, encounter, clinical record, billing, inventory, user, audit, and configuration.",
     ["Data Model Overview",
      "Patient Data Model",
      "Encounter Data Model",
      "Clinical Record Data Model",
      "Billing & Invoice Data Model",
      "Inventory Data Model",
      "User & Role Data Model",
      "Audit Log Data Model",
      "Configuration Data Model",
      "Model Versioning Strategy",
      "Model Migration Patterns",
      "Related Documents"]),

    ("04_DATABASE/VALIDATIONS.md",
     "Validations",
     "All data validation rules — field-level, entity-level, business-rule, cross-entity — with error handling, localization, and testing.",
     ["Validation Overview",
      "Validation Strategy",
      "Field-Level Validations",
      "Entity-Level Validations",
      "Business Rule Validations",
      "Cross-Entity Validations",
      "Validation Error Handling",
      "Validation Error Localization",
      "Custom Validators",
      "Validation Testing",
      "Validation Performance",
      "Related Documents"]),

    ("04_DATABASE/STORAGE.md",
     "Storage",
     "The storage strategy for structured data, files, documents, images, backups, and archives — including tiers, quotas, and monitoring.",
     ["Storage Overview",
      "Database Storage",
      "File & Document Storage",
      "Medical Image Storage",
      "Backup Storage",
      "Archive Storage",
      "Storage Tiers",
      "Storage Quotas",
      "Storage Monitoring",
      "Storage Lifecycle Policies",
      "Storage Cost Optimization",
      "Related Documents"]),

    # ====================================================================
    # 05_UI_UX (renumbered from 04)
    # ====================================================================
    ("05_UI_UX/DESIGN_BIBLE.md",
     "Design Bible",
     "The master design reference for the Ibn Hayan Healthcare Operating System — philosophy, principles, brand identity, visual language, and quality bar.",
     ["Design Philosophy",
      "Design Principles",
      "Brand Identity",
      "Visual Language",
      "Design Tone & Voice",
      "Design Quality Bar",
      "Design Review Process",
      "Design Documentation Standards",
      "Design Governance",
      "Design Evolution",
      "Related Documents"]),

    ("05_UI_UX/DESIGN_SYSTEM.md",
     "Design System",
     "The complete design system — tokens, components, patterns, layout, color, typography, spacing, iconography, motion, and theming.",
     ["Design System Overview",
      "Design Tokens",
      "Component System",
      "Pattern Library",
      "Layout System",
      "Color System",
      "Typography System",
      "Spacing System",
      "Iconography System",
      "Motion System",
      "Theming System",
      "Design System Governance",
      "Related Documents"]),

    ("05_UI_UX/COMPONENT_LIBRARY.md",
     "Component Library",
     "The full UI component catalog — primitives, forms, navigation, data display, feedback, overlays, layouts, and specialty clinical components.",
     ["Component Overview",
      "Primitive Components",
      "Form Components",
      "Navigation Components",
      "Data Display Components",
      "Feedback Components",
      "Overlay Components",
      "Layout Components",
      "Specialty Clinical Components",
      "Component API Standards",
      "Component Lifecycle",
      "Component Documentation Standards",
      "Related Documents"]),

    ("05_UI_UX/COLORS.md",
     "Colors",
     "The complete color palette — primary, secondary, semantic, neutral, and specialty colors — with tokens, accessibility, and dark theme support.",
     ["Color Philosophy",
      "Primary Palette",
      "Secondary Palette",
      "Semantic Colors (Success, Warning, Danger, Info)",
      "Neutral Palette",
      "Specialty Colors",
      "Color Tokens",
      "Color Accessibility",
      "Dark Theme Color Mapping",
      "Color Usage Guidelines",
      "Color in Medical Context",
      "Related Documents"]),

    ("05_UI_UX/TYPOGRAPHY.md",
     "Typography",
     "The typography system — font families, type scale, line height, letter spacing, weights, multilingual support, and usage guidelines.",
     ["Typography Philosophy",
      "Font Family Selection",
      "Type Scale",
      "Line Height",
      "Letter Spacing",
      "Font Weights",
      "Text Styles",
      "Multilingual Typography",
      "Arabic Typography",
      "Typography Tokens",
      "Typography Usage Guidelines",
      "Related Documents"]),

    ("05_UI_UX/ICONOGRAPHY.md",
     "Iconography",
     "The icon system — library, categories, sizing, styling, naming, custom icons, accessibility, and extension process.",
     ["Icon Philosophy",
      "Icon Library",
      "Icon Categories",
      "Icon Sizing",
      "Icon Styling",
      "Icon Naming Conventions",
      "Custom Icons",
      "Icon Accessibility",
      "Icon Usage Guidelines",
      "Icon Extension Process",
      "Medical & Clinical Icons",
      "Related Documents"]),

    ("05_UI_UX/LAYOUTS.md",
     "Layouts",
     "All layout patterns — grid system, page layouts, application shell, sidebars, content, forms, tables, cards, modals, and print.",
     ["Layout Philosophy",
      "Grid System",
      "Page Layouts",
      "Application Shell",
      "Sidebar Layouts",
      "Content Layouts",
      "Form Layouts",
      "Table Layouts",
      "Card Layouts",
      "Modal & Overlay Layouts",
      "Dashboard Layouts",
      "Print Layouts",
      "Related Documents"]),

    ("05_UI_UX/RESPONSIVE_RULES.md",
     "Responsive Rules",
     "The responsive design rules — breakpoints, mobile-first approach, device categories, patterns, and testing matrix.",
     ["Responsive Philosophy",
      "Breakpoint System",
      "Mobile-First Approach",
      "Device Categories",
      "Responsive Patterns",
      "Touch Target Guidelines",
      "Responsive Navigation",
      "Responsive Tables",
      "Responsive Forms",
      "Testing Matrix",
      "Progressive Enhancement",
      "Related Documents"]),

    ("05_UI_UX/ACCESSIBILITY.md",
     "Accessibility",
     "Accessibility standards — WCAG compliance, semantic HTML, ARIA, keyboard navigation, screen reader support, color contrast, and testing.",
     ["Accessibility Philosophy",
      "WCAG Compliance Level",
      "Semantic HTML Standards",
      "ARIA Guidelines",
      "Keyboard Navigation",
      "Screen Reader Support",
      "Color Contrast Standards",
      "Focus Management",
      "Accessible Forms",
      "Accessibility Testing",
      "Accessibility Audit Process",
      "Related Documents"]),

    ("05_UI_UX/ANIMATIONS.md",
     "Animations",
     "The motion design system — principles, easing, duration, transitions, micro-interactions, loading states, and reduced motion support.",
     ["Motion Philosophy",
      "Motion Principles",
      "Easing Functions",
      "Duration Standards",
      "Transition Patterns",
      "Micro-Interactions",
      "Loading & Skeleton States",
      "Page Transitions",
      "Animation Performance",
      "Reduced Motion Support",
      "Animation Documentation",
      "Related Documents"]),

    # ====================================================================
    # 06_CLINIC_TYPES (renumbered from 05)
    # ====================================================================
    ("06_CLINIC_TYPES/GENERAL.md",
     "General Practice & Multi-Specialty Clinics",
     "Configuration, modules, workflows, and considerations for general practice and multi-specialty clinic facilities on the Ibn Hayan platform.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Third-Party Integrations",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/DENTAL.md",
     "Dental Clinics",
     "Specialty configuration for dental clinics — dental charting, treatment planning, imaging, materials inventory, and procedure library.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Dental Charting",
      "Treatment Planning",
      "Dental Imaging Integration",
      "Dental Materials Inventory",
      "Procedures Library",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/DERMATOLOGY.md",
     "Dermatology & Laser Centers",
     "Specialty configuration for dermatology and laser centers — skin lesion tracking, treatment sessions, before/after imaging, and laser records.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Skin Lesion Tracking",
      "Treatment Session Records",
      "Before/After Imaging",
      "Laser Treatment Records",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/PLASTIC_SURGERY.md",
     "Plastic Surgery & Cosmetic Centers",
     "Specialty configuration for plastic surgery and cosmetic centers — pre-op assessment, surgical planning, procedure documentation, and recovery tracking.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Pre-Operative Assessment",
      "Surgical Planning",
      "Procedure Documentation",
      "Recovery Tracking",
      "Before/After Imaging",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/PEDIATRICS.md",
     "Pediatrics Clinics",
     "Specialty configuration for pediatrics clinics — growth charts, vaccination schedules, developmental milestones, and pediatric dosage calculations.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Growth Charts & Percentiles",
      "Vaccination Schedules",
      "Developmental Milestones",
      "Pediatric Dosage Calculations",
      "Parent/Guardian Portal",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/INTERNAL_MEDICINE.md",
     "Internal Medicine Clinics",
     "Specialty configuration for internal medicine — chronic disease management, medication management, lab tracking, and comorbidity management.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Chronic Disease Management",
      "Medication Management",
      "Lab Result Tracking",
      "Comorbidity Management",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/CARDIOLOGY.md",
     "Cardiology Clinics",
     "Specialty configuration for cardiology — ECG management, echocardiogram records, cardiac catheterization, and cardiovascular risk assessment.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "ECG Management",
      "Echocardiogram Records",
      "Cardiac Catheterization Records",
      "Cardiovascular Risk Assessment",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Third-Party Integrations",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/ENT.md",
     "ENT (Ear, Nose, Throat) Clinics",
     "Specialty configuration for ENT clinics — audiometry, endoscopy, hearing aid management, and sinus treatment records.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Audiometry Records",
      "Endoscopy Documentation",
      "Hearing Aid Management",
      "Sinus Treatment Records",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/OPHTHALMOLOGY.md",
     "Ophthalmology Clinics",
     "Specialty configuration for ophthalmology — visual acuity, slit lamp findings, intraocular pressure, and refraction records.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Visual Acuity Records",
      "Slit Lamp Findings",
      "Intraocular Pressure Records",
      "Refraction Records",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/ORTHOPEDICS.md",
     "Orthopedics Clinics",
     "Specialty configuration for orthopedics — musculoskeletal assessment, range of motion tracking, surgical records, and rehabilitation planning.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Musculoskeletal Assessment",
      "Range of Motion Tracking",
      "Surgical Records",
      "Rehabilitation Planning",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/GYNECOLOGY.md",
     "Gynecology & Obstetrics Clinics",
     "Specialty configuration for gynecology and obstetrics — menstrual history, pregnancy tracking, prenatal records, and contraception management.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Menstrual History Records",
      "Pregnancy Tracking",
      "Prenatal Records",
      "Contraception Management",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/UROLOGY.md",
     "Urology Clinics",
     "Specialty configuration for urology — uroflowmetry, prostate assessment, stone management, and urodynamic studies.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Uroflowmetry Records",
      "Prostate Assessment",
      "Stone Management",
      "Urodynamic Studies",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/PSYCHIATRY.md",
     "Psychiatry Clinics",
     "Specialty configuration for psychiatry — mental status examination, medication management, therapy session notes, and risk assessment.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Mental Status Examination",
      "Psychiatric Medication Management",
      "Therapy Session Notes",
      "Risk Assessment & Safety Planning",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Privacy & Confidentiality Considerations",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/NEUROLOGY.md",
     "Neurology Clinics",
     "Specialty configuration for neurology — neurological examination, EEG records, stroke assessment, and cognitive assessment.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Neurological Examination",
      "EEG Records",
      "Stroke Assessment",
      "Cognitive Assessment",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/PHYSIOTHERAPY.md",
     "Physiotherapy & Rehabilitation Centers",
     "Specialty configuration for physiotherapy — assessment forms, treatment plans, progress tracking, and exercise prescription.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Assessment Forms",
      "Treatment Plans",
      "Progress Tracking",
      "Exercise Prescription",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/LABORATORY.md",
     "Laboratory Centers",
     "Specialty configuration for medical laboratories — test catalog, sample management, result reporting, quality control, and instrument integration.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Test Catalog",
      "Sample Management",
      "Result Reporting",
      "Quality Control",
      "Instrument Integration",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/RADIOLOGY.md",
     "Radiology & Imaging Centers",
     "Specialty configuration for radiology and imaging centers — modalities, study management, report templates, and PACS integration.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Imaging Modalities",
      "Study Management",
      "Report Templates",
      "PACS Integration",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/PHARMACY.md",
     "Pharmacy",
     "Specialty configuration for pharmacy operations — medication catalog, prescription management, dispensing workflow, and drug interactions.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Medication Catalog",
      "Prescription Management",
      "Dispensing Workflow",
      "Drug Interaction Checking",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    ("06_CLINIC_TYPES/HOSPITAL.md",
     "Hospitals",
     "Specialty configuration for hospitals — department management, bed management, emergency, surgical suite, ICU, wards, and discharge planning.",
     ["Specialty Overview",
      "Target Facilities",
      "Recommended Modules",
      "Department Management",
      "Bed Management",
      "Emergency Department",
      "Surgical Suite Management",
      "ICU Management",
      "Ward Management",
      "Discharge Planning",
      "Specialty Workflows",
      "Specialty Data Models",
      "Forms & Templates",
      "Reports & Analytics",
      "Role & Permission Recommendations",
      "Configuration Defaults",
      "Onboarding Checklist",
      "Sample Use Cases",
      "Best Practices",
      "Related Documents"]),

    # ====================================================================
    # 07_MODULES (renumbered from 06)
    # ====================================================================
    ("07_MODULES/PATIENTS.md",
     "Patients Module",
     "The Patients module — registration, demographics, medical history, patient portal, and patient communication management.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Patient Registration",
      "Patient Demographics",
      "Medical History",
      "Patient Portal",
      "Patient Communication",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/APPOINTMENTS.md",
     "Appointments Module",
     "The Appointments module — calendar management, booking rules, reminders, no-show management, and recurring appointments.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Calendar Management",
      "Booking Rules & Validation",
      "Reminders & Notifications",
      "No-Show Management",
      "Recurring Appointments",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/DOCTORS.md",
     "Doctors Module",
     "The Doctors module — profiles, specializations, schedules, performance metrics, and compensation management.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Doctor Profiles",
      "Specializations & Credentials",
      "Schedules & Availability",
      "Performance Metrics",
      "Compensation Management",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/RECEPTION.md",
     "Reception Module",
     "The Reception module — patient check-in, queue management, walk-in handling, and visitor management.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Patient Check-In",
      "Queue Management",
      "Walk-In Handling",
      "Visitor Management",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/BILLING.md",
     "Billing Module",
     "The Billing module — invoice generation, payment processing, insurance claims, refunds, and financial reporting.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Invoice Generation",
      "Payment Processing",
      "Insurance Claims",
      "Refunds & Adjustments",
      "Financial Reporting",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/ACCOUNTING.md",
     "Accounting Module",
     "The Accounting module — chart of accounts, general ledger, financial statements, tax management, and multi-currency support.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Chart of Accounts",
      "General Ledger",
      "Financial Statements",
      "Tax Management",
      "Multi-Currency Support",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/INVENTORY.md",
     "Inventory Module",
     "The Inventory module — stock management, procurement, supplier management, stocktaking, and expiry tracking.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Stock Management",
      "Procurement",
      "Supplier Management",
      "Stocktaking",
      "Expiry Tracking",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/HR.md",
     "Human Resources Module",
     "The HR module — employee records, attendance, payroll, leave management, and performance reviews.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Employee Records",
      "Attendance Management",
      "Payroll",
      "Leave Management",
      "Performance Reviews",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/REPORTS.md",
     "Reports Module",
     "The Reports module — standard reports, custom reports, dashboards, scheduled reports, and export options.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Standard Reports",
      "Custom Report Builder",
      "Dashboards",
      "Scheduled Reports",
      "Export Options",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/NOTIFICATIONS.md",
     "Notifications Module",
     "The Notifications module — channels, templates, rules, patient notifications, and staff notifications.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Notification Channels",
      "Notification Templates",
      "Notification Rules & Triggers",
      "Patient Notifications",
      "Staff Notifications",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/CRM.md",
     "CRM Module",
     "The CRM module — lead management, patient acquisition, marketing campaigns, loyalty programs, and patient feedback.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Lead Management",
      "Patient Acquisition",
      "Marketing Campaigns",
      "Loyalty Programs",
      "Patient Feedback",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/SETTINGS.md",
     "Settings Module",
     "The Settings module — general settings, module settings, user settings, system configuration, and integration settings.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "General Settings",
      "Module Settings",
      "User Settings",
      "System Configuration",
      "Integration Settings",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Permissions",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/SUBSCRIPTIONS.md",
     "Subscriptions Module",
     "The Subscriptions module — plans, billing cycles, upgrades/downgrades, trial management, and subscription analytics.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Subscription Plans",
      "Billing Cycles",
      "Upgrades & Downgrades",
      "Trial Management",
      "Subscription Analytics",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    ("07_MODULES/AUDIT_LOGS.md",
     "Audit Logs Module",
     "The Audit Logs module — event types, audit trail, log retention, compliance reporting, and audit search.",
     ["Module Overview",
      "Module Purpose & Scope",
      "Key Features",
      "Audit Event Types",
      "Audit Trail",
      "Log Retention Policies",
      "Compliance Reporting",
      "Audit Search & Filtering",
      "User Roles",
      "Workflows",
      "Data Models",
      "Integrations",
      "Configuration",
      "Permissions",
      "Reports",
      "API Surface",
      "Future Enhancements",
      "Related Documents"]),

    # ====================================================================
    # 08_INTEGRATIONS (NEW)
    # ====================================================================
    ("08_INTEGRATIONS/PAYMENT_GATEWAYS.md",
     "Payment Gateways",
     "Integration standards for payment gateway providers — supported providers, transaction flows, refunds, webhooks, security, and reconciliation.",
     ["Payment Gateways Overview",
      "Supported Providers",
      "Integration Architecture",
      "Transaction Flows",
      "Refund & Chargeback Handling",
      "Webhook Handling",
      "Security & PCI Compliance",
      "Currency & Multi-Currency",
      "Reconciliation",
      "Error Handling & Retries",
      "Testing & Sandbox",
      "Configuration",
      "Monitoring & Alerts",
      "Related Documents"]),

    ("08_INTEGRATIONS/SMS.md",
     "SMS Integration",
     "Integration standards for SMS service providers — supported providers, message flows, templates, delivery reports, and compliance.",
     ["SMS Integration Overview",
      "Supported Providers",
      "Integration Architecture",
      "Message Flows",
      "Template Management",
      "Delivery Reports",
      "Compliance & Opt-Out",
      "International & Localization",
      "Error Handling & Retries",
      "Testing & Sandbox",
      "Configuration",
      "Monitoring & Alerts",
      "Related Documents"]),

    ("08_INTEGRATIONS/EMAIL.md",
     "Email Integration",
     "Integration standards for email service providers — supported providers, message flows, templates, attachments, and deliverability.",
     ["Email Integration Overview",
      "Supported Providers",
      "Integration Architecture",
      "Message Flows",
      "Template Management",
      "Attachments & Embedded Images",
      "Deliverability Best Practices",
      "Authentication (SPF, DKIM, DMARC)",
      "Bounce & Complaint Handling",
      "Testing & Sandbox",
      "Configuration",
      "Monitoring & Alerts",
      "Related Documents"]),

    ("08_INTEGRATIONS/WHATSAPP.md",
     "WhatsApp Integration",
     "Integration standards for WhatsApp Business API — provider selection, message types, templates, opt-in management, and compliance.",
     ["WhatsApp Integration Overview",
      "Supported Providers",
      "Integration Architecture",
      "Message Types (Session, Template)",
      "Template Management",
      "Opt-In & Opt-Out Management",
      "Media & Document Support",
      "Compliance & Privacy",
      "Error Handling & Retries",
      "Testing & Sandbox",
      "Configuration",
      "Monitoring & Alerts",
      "Related Documents"]),

    ("08_INTEGRATIONS/LAB_DEVICES.md",
     "Lab Device Integration",
     "Integration standards for laboratory instruments and analyzers — protocols, bi-directional communication, result parsing, and quality control.",
     ["Lab Device Integration Overview",
      "Supported Protocols (HL7, ASTM, POCT1-A)",
      "Supported Instruments & Analyzers",
      "Integration Architecture",
      "Bi-Directional Communication",
      "Result Parsing & Validation",
      "Quality Control Integration",
      "Sample Barcoding & Tracking",
      "Error Handling & Retries",
      "Testing & Simulation",
      "Configuration",
      "Monitoring & Alerts",
      "Related Documents"]),

    ("08_INTEGRATIONS/DICOM.md",
     "DICOM Integration",
     "Integration standards for medical imaging using DICOM — modalities, PACS, worklists, storage, transmission, and viewer integration.",
     ["DICOM Integration Overview",
      "DICOM Standard & Conformance",
      "Supported Modalities",
      "PACS Integration",
      "DICOM Worklist (MWL)",
      "DICOM Storage (C-STORE)",
      "DICOM Query/Retrieve (C-FIND, C-MOVE)",
      "DICOM Transmission & Security",
      "Viewer Integration",
      "Image Lifecycle & Retention",
      "Testing & Validation",
      "Configuration",
      "Monitoring & Alerts",
      "Related Documents"]),

    ("08_INTEGRATIONS/HL7_FHIR.md",
     "HL7 & FHIR Integration",
     "Integration standards for healthcare interoperability using HL7 v2, HL7 v3, and FHIR — resources, profiles, terminologies, and exchange patterns.",
     ["HL7 & FHIR Overview",
      "HL7 v2 Integration",
      "HL7 v3 & CDA Integration",
      "FHIR R4 Implementation",
      "FHIR Resources & Profiles",
      "Terminology Services",
      "RESTful API Conformance",
      "Subscription & Notification",
      "Patient Identity Cross-Referencing",
      "Security & OAuth2/SMART",
      "Testing & Validation",
      "Configuration",
      "Monitoring & Alerts",
      "Related Documents"]),

    ("08_INTEGRATIONS/NATIONAL_HEALTH_SYSTEMS.md",
     "National Health Systems Integration",
     "Integration standards for national and regional health systems — country-specific connectors, e-prescription, insurance, and reporting.",
     ["National Health Systems Overview",
      "Country-Specific Connectors",
      "National Patient Identifier Resolution",
      "E-Prescription Integration",
      "National Insurance & Claims",
      "Public Health Reporting",
      "Vaccination Registry Integration",
      "Notifiable Disease Reporting",
      "Cross-Border Data Exchange",
      "Compliance & Certification",
      "Testing & Certification",
      "Configuration",
      "Monitoring & Alerts",
      "Related Documents"]),

    # ====================================================================
    # 09_SECURITY (renumbered from 07) — includes COMPLIANCE subfolder
    # ====================================================================
    ("09_SECURITY/AUTHENTICATION.md",
     "Authentication",
     "Authentication architecture and policies — methods, password policies, MFA, SSO, session management, biometrics, and security considerations.",
     ["Authentication Overview",
      "Authentication Methods",
      "Password Policies",
      "Multi-Factor Authentication (MFA)",
      "Single Sign-On (SSO)",
      "Session Management",
      "Biometric Authentication",
      "Authentication Flows",
      "Authentication Error Handling",
      "Security Considerations",
      "Authentication Testing",
      "Related Documents"]),

    ("09_SECURITY/AUTHORIZATION.md",
     "Authorization",
     "Authorization architecture — model, access control types, resource/action/field authorization, policies, enforcement, and audit.",
     ["Authorization Overview",
      "Authorization Model",
      "Access Control Types (RBAC, ABAC, PBAC)",
      "Resource Authorization",
      "Action Authorization",
      "Field Authorization",
      "Contextual Authorization",
      "Authorization Policies",
      "Authorization Enforcement",
      "Authorization Audit",
      "Authorization Testing",
      "Related Documents"]),

    ("09_SECURITY/ROLES_AND_PERMISSIONS.md",
     "Roles & Permissions",
     "The complete role and permission catalog — definitions, matrices, custom roles, hierarchy, assignment, and lifecycle.",
     ["Role Overview",
      "Role Definitions",
      "Permission Catalog",
      "Role-Permission Matrix",
      "Custom Roles",
      "Role Hierarchy",
      "Role Assignment Workflow",
      "Role Lifecycle",
      "Permission Inheritance",
      "Role-Based Access Control (RBAC)",
      "Permission Review Process",
      "Related Documents"]),

    ("09_SECURITY/BACKUP.md",
     "Backup",
     "Backup strategy and operations — types, frequency, storage, encryption, verification, restoration, monitoring, and compliance.",
     ["Backup Overview",
      "Backup Strategy",
      "Backup Types (Full, Incremental, Differential)",
      "Backup Frequency",
      "Backup Storage",
      "Backup Encryption",
      "Backup Verification",
      "Backup Restoration Procedures",
      "Backup Monitoring",
      "Backup Compliance",
      "Backup Documentation",
      "Related Documents"]),

    ("09_SECURITY/RECOVERY.md",
     "Recovery",
     "Recovery strategy and procedures — RTO/RPO objectives, disaster recovery, business continuity, testing, and incident response.",
     ["Recovery Overview",
      "Recovery Strategy",
      "Recovery Objectives (RTO & RPO)",
      "Disaster Recovery Plan",
      "Business Continuity Plan",
      "Recovery Procedures",
      "Recovery Testing",
      "Recovery Documentation",
      "Incident Response Plan",
      "Post-Incident Review",
      "Related Documents"]),

    ("09_SECURITY/AUDIT.md",
     "Audit",
     "Security audit framework — scope, events, logging, trail, reports, retention, review process, and compliance audits.",
     ["Audit Overview",
      "Audit Scope",
      "Audit Event Categories",
      "Audit Logging",
      "Audit Trail Integrity",
      "Audit Reports",
      "Audit Log Retention",
      "Audit Review Process",
      "Compliance Audits",
      "Audit Tools & Automation",
      "Related Documents"]),

    # ----- 09_SECURITY/COMPLIANCE subfolder -----
    ("09_SECURITY/COMPLIANCE/HIPAA.md",
     "HIPAA Compliance",
     "HIPAA compliance framework for the Ibn Hayan Healthcare Operating System — Privacy Rule, Security Rule, Breach Notification, and BAAs.",
     ["HIPAA Overview",
      "HIPAA Privacy Rule",
      "HIPAA Security Rule",
      "Administrative Safeguards",
      "Physical Safeguards",
      "Technical Safeguards",
      "Breach Notification Rule",
      "Business Associate Agreements (BAAs)",
      "HIPAA Risk Assessment",
      "HIPAA Audit & Documentation",
      "HIPAA Training Requirements",
      "Patient Rights Under HIPAA",
      "HIPAA Compliance Checklist",
      "Related Documents"]),

    ("09_SECURITY/COMPLIANCE/GDPR.md",
     "GDPR Compliance",
     "GDPR compliance framework — lawful bases, data subject rights, DPIA, DPO role, cross-border transfers, and breach notification.",
     ["GDPR Overview",
      "Lawful Bases for Processing",
      "Data Subject Rights",
      "Consent Management",
      "Data Protection Impact Assessment (DPIA)",
      "Data Protection Officer (DPO) Role",
      "Cross-Border Data Transfers",
      "Privacy by Design & Default",
      "Records of Processing Activities (ROPA)",
      "Personal Data Breach Notification",
      "GDPR Audit & Documentation",
      "GDPR Training Requirements",
      "GDPR Compliance Checklist",
      "Related Documents"]),

    ("09_SECURITY/COMPLIANCE/DATA_RETENTION.md",
     "Data Retention Policy",
     "The data retention framework — retention periods by data category, legal hold, disposal, archiving, and patient data rights.",
     ["Data Retention Overview",
      "Retention Periods by Data Category",
      "Clinical Data Retention",
      "Financial Data Retention",
      "Operational Data Retention",
      "Audit Log Retention",
      "Backup Retention",
      "Legal Hold Procedures",
      "Data Disposal & Destruction",
      "Archiving Strategy",
      "Patient Data Rights & Deletion",
      "Regional Variations",
      "Retention Compliance Audit",
      "Related Documents"]),

    ("09_SECURITY/COMPLIANCE/MEDICAL_RECORD_POLICY.md",
     "Medical Record Policy",
     "The medical record governance policy — ownership, access, amendment, correction, disclosure, and lifecycle of medical records.",
     ["Medical Record Policy Overview",
      "Medical Record Ownership",
      "Medical Record Access",
      "Amendment & Correction",
      "Addendum Procedures",
      "Disclosure & Release",
      "Record Format & Structure",
      "Record Authentication & Signing",
      "Record Integrity & Immutability",
      "Record Lifecycle Management",
      "Patient Access Rights",
      "Third-Party Access",
      "Audit of Record Access",
      "Related Documents"]),

    ("09_SECURITY/COMPLIANCE/PRIVACY_POLICY.md",
     "Privacy Policy",
     "The privacy policy framework for the Ibn Hayan Healthcare Operating System — collection, use, sharing, patient rights, and transparency.",
     ["Privacy Policy Overview",
      "Information We Collect",
      "How We Use Information",
      "Legal Basis for Processing",
      "Information Sharing & Disclosure",
      "Patient Rights",
      "Data Retention",
      "Data Security",
      "Cookies & Tracking Technologies",
      "International Data Transfers",
      "Children's Privacy",
      "Policy Updates & Notifications",
      "Contact & Complaints",
      "Related Documents"]),

    ("09_SECURITY/COMPLIANCE/SECURITY_GUIDELINES.md",
     "Security Guidelines",
     "Security guidelines for the Ibn Hayan Healthcare Operating System — operations, infrastructure, application, data, and personnel security.",
     ["Security Guidelines Overview",
      "Infrastructure Security",
      "Application Security",
      "Data Security",
      "Network Security",
      "Endpoint Security",
      "Identity & Access Security",
      "Operational Security",
      "Personnel Security",
      "Incident Response Guidelines",
      "Vulnerability Management",
      "Security Awareness Training",
      "Third-Party Security",
      "Related Documents"]),

    # ====================================================================
    # 10_API (renumbered from 08)
    # ====================================================================
    ("10_API/API_GUIDELINES.md",
     "API Guidelines",
     "The API design guidelines governing all public and internal APIs — RESTful principles, naming, formats, status codes, pagination, security, and versioning.",
     ["API Design Philosophy",
      "RESTful Principles",
      "Naming Conventions",
      "Request & Response Formats",
      "HTTP Methods",
      "HTTP Status Codes",
      "Pagination",
      "Filtering & Sorting",
      "Rate Limiting",
      "API Security",
      "Versioning Strategy",
      "API Documentation Standards",
      "Related Documents"]),

    ("10_API/ENDPOINTS.md",
     "Endpoints",
     "The complete API endpoint catalog organized by domain — authentication, patients, appointments, clinical, billing, inventory, reporting, configuration, and webhooks.",
     ["Endpoint Catalog Overview",
      "Authentication Endpoints",
      "Patient Endpoints",
      "Appointment Endpoints",
      "Clinical Endpoints",
      "Billing Endpoints",
      "Inventory Endpoints",
      "Reporting Endpoints",
      "Configuration Endpoints",
      "Webhook Endpoints",
      "Endpoint Deprecation",
      "Related Documents"]),

    ("10_API/ERROR_CODES.md",
     "Error Codes",
     "The complete error code reference — HTTP status codes, application error codes, validation errors, authentication errors, and error response format.",
     ["Error Code Format",
      "HTTP Status Codes",
      "Application Error Codes",
      "Validation Errors",
      "Authentication Errors",
      "Authorization Errors",
      "Business Logic Errors",
      "Integration Errors",
      "Error Response Format",
      "Error Handling Best Practices",
      "Related Documents"]),

    ("10_API/VERSIONING.md",
     "API Versioning",
     "API versioning strategy — semantic versioning, lifecycle, backward compatibility, deprecation, migration guides, and sunset policy.",
     ["Versioning Strategy",
      "Semantic Versioning",
      "API Version Lifecycle",
      "Backward Compatibility Policy",
      "Deprecation Policy",
      "Migration Guides",
      "Version Documentation",
      "Breaking Changes Policy",
      "Version Support Matrix",
      "Sunset Policy",
      "Related Documents"]),

    # ====================================================================
    # 11_TESTING (renumbered from 09)
    # ====================================================================
    ("11_TESTING/TESTING_STRATEGY.md",
     "Testing Strategy",
     "The overall testing strategy — philosophy, pyramid, coverage goals, environments, data management, automation, tools, and quality metrics.",
     ["Testing Philosophy",
      "Testing Pyramid",
      "Test Coverage Goals",
      "Testing Environments",
      "Test Data Management",
      "Test Automation Strategy",
      "Testing Tools",
      "Testing Roles & Responsibilities",
      "Testing Process",
      "Quality Metrics",
      "Related Documents"]),

    ("11_TESTING/UNIT_TESTS.md",
     "Unit Tests",
     "Unit testing standards — framework, structure, mocking, data builders, coverage requirements, naming conventions, and best practices.",
     ["Unit Testing Overview",
      "Unit Testing Framework",
      "Test Structure",
      "Mocking & Stubbing",
      "Test Data Builders",
      "Coverage Requirements",
      "Naming Conventions",
      "Test Performance",
      "Best Practices",
      "Common Pitfalls",
      "Related Documents"]),

    ("11_TESTING/INTEGRATION_TESTS.md",
     "Integration Tests",
     "Integration testing standards — strategy, environment setup, database testing, API integration, third-party integration, and end-to-end scenarios.",
     ["Integration Testing Overview",
      "Integration Test Strategy",
      "Test Environment Setup",
      "Database Integration Testing",
      "API Integration Testing",
      "Third-Party Integration Testing",
      "End-to-End Scenarios",
      "Test Data Management",
      "Integration Test CI Pipeline",
      "Best Practices",
      "Related Documents"]),

    ("11_TESTING/UI_TESTS.md",
     "UI Tests",
     "UI testing standards — framework, component testing, page testing, visual regression, cross-browser, accessibility, and mobile testing.",
     ["UI Testing Overview",
      "UI Testing Framework",
      "Component Testing",
      "Page Testing",
      "Visual Regression Testing",
      "Cross-Browser Testing",
      "Accessibility Testing",
      "Mobile Testing",
      "Test Recording & Playback",
      "Best Practices",
      "Related Documents"]),

    ("11_TESTING/PERFORMANCE_TESTS.md",
     "Performance Tests",
     "Performance testing standards — metrics, load testing, stress testing, spike testing, endurance testing, scalability testing, and tools.",
     ["Performance Testing Overview",
      "Performance Metrics",
      "Load Testing",
      "Stress Testing",
      "Spike Testing",
      "Endurance Testing",
      "Scalability Testing",
      "Performance Testing Tools",
      "Performance Baselines",
      "Performance Monitoring",
      "Related Documents"]),

    # ====================================================================
    # 12_ADR (NEW)
    # ====================================================================
    # NOTE: ADR files use a separate ADR_TEMPLATE — handled in main()
    # See ADR_FILES list below.

    # ====================================================================
    # 13_DEPLOYMENT (renumbered from 10)
    # ====================================================================
    ("13_DEPLOYMENT/DEVELOPMENT.md",
     "Development Environment",
     "The development environment setup — local setup, workflow, tools, code style enforcement, git workflow, branching, and pull request process.",
     ["Development Environment Overview",
      "Local Setup Guide",
      "Development Workflow",
      "Development Tools",
      "Code Style Enforcement",
      "Git Workflow",
      "Branching Strategy",
      "Pull Request Process",
      "Code Review Guidelines",
      "Development Database",
      "Development Cache & Queues",
      "Related Documents"]),

    ("13_DEPLOYMENT/STAGING.md",
     "Staging Environment",
     "The staging environment — setup, deployment process, smoke testing, acceptance testing, data, access, monitoring, and promotion to production.",
     ["Staging Environment Overview",
      "Staging Setup",
      "Deployment Process",
      "Smoke Testing",
      "Acceptance Testing",
      "Staging Data Management",
      "Staging Access Control",
      "Staging Monitoring",
      "Staging Issue Handling",
      "Promotion to Production",
      "Related Documents"]),

    ("13_DEPLOYMENT/PRODUCTION.md",
     "Production Environment",
     "The production environment — architecture, deployment process, blue-green, canary, rollback, monitoring, support, on-call, and security.",
     ["Production Environment Overview",
      "Production Architecture",
      "Deployment Process",
      "Blue-Green Deployment",
      "Canary Releases",
      "Rollback Procedures",
      "Production Monitoring",
      "Production Support",
      "On-Call Procedures",
      "Production Security",
      "Related Documents"]),

    ("13_DEPLOYMENT/BACKUPS.md",
     "Backups",
     "Production backup operations — strategy, schedule, storage, encryption, verification, restoration, monitoring, compliance, and documentation.",
     ["Backup Overview",
      "Backup Strategy",
      "Backup Schedule",
      "Backup Storage",
      "Backup Encryption",
      "Backup Verification",
      "Backup Restoration",
      "Backup Monitoring",
      "Backup Compliance",
      "Backup Documentation",
      "Related Documents"]),

    ("13_DEPLOYMENT/DEVOPS.md",
     "DevOps",
     "DevOps practices and tooling — CI/CD pipeline, infrastructure as code, containerization, orchestration, monitoring, logging, alerting, and incident management.",
     ["DevOps Overview",
      "CI/CD Pipeline",
      "Infrastructure as Code",
      "Containerization",
      "Orchestration",
      "Monitoring & Logging",
      "Alerting",
      "Incident Management",
      "DevOps Tools",
      "DevOps Best Practices",
      "Related Documents"]),

    # ====================================================================
    # 14_FUTURE (renumbered from 11)
    # ====================================================================
    ("14_FUTURE/AI_ROADMAP.md",
     "AI Roadmap",
     "The artificial intelligence strategy and roadmap — use cases, models, integration points, ethics, governance, performance, data requirements, and risks.",
     ["AI Strategy",
      "AI Use Cases",
      "AI Roadmap",
      "AI Models & Architectures",
      "AI Integration Points",
      "AI Ethics & Bias",
      "AI Governance",
      "AI Performance Metrics",
      "AI Data Requirements",
      "AI Risks & Mitigations",
      "Related Documents"]),

    ("14_FUTURE/MOBILE.md",
     "Mobile Strategy",
     "The mobile application strategy — platforms, architecture, features, offline support, security, distribution, roadmap, and testing.",
     ["Mobile Strategy",
      "Mobile Platforms",
      "Mobile Architecture",
      "Mobile Features",
      "Offline Support",
      "Mobile Security",
      "Mobile Distribution",
      "Mobile Roadmap",
      "Mobile Testing",
      "Mobile Maintenance",
      "Related Documents"]),

    ("14_FUTURE/CLOUD.md",
     "Cloud Strategy",
     "The cloud strategy — providers, architecture, multi-cloud, migration, cost optimization, security, monitoring, roadmap, and compliance.",
     ["Cloud Strategy",
      "Cloud Providers",
      "Cloud Architecture",
      "Multi-Cloud Strategy",
      "Cloud Migration",
      "Cloud Cost Optimization",
      "Cloud Security",
      "Cloud Monitoring",
      "Cloud Roadmap",
      "Cloud Compliance",
      "Related Documents"]),

    ("14_FUTURE/ENTERPRISE.md",
     "Enterprise Strategy",
     "The enterprise strategy — features, deployment, integration, security, support, SLAs, pricing, onboarding, and roadmap.",
     ["Enterprise Strategy",
      "Enterprise Features",
      "Enterprise Deployment",
      "Enterprise Integration",
      "Enterprise Security",
      "Enterprise Support",
      "Enterprise SLAs",
      "Enterprise Pricing",
      "Enterprise Onboarding",
      "Enterprise Roadmap",
      "Related Documents"]),

    ("14_FUTURE/IDEAS.md",
     "Ideas & Innovation Pipeline",
     "The ideas and innovation pipeline — submission process, evaluation, prioritization, archive, research initiatives, experiments, and community suggestions.",
     ["Ideas Process Overview",
      "Submitted Ideas",
      "Idea Evaluation Framework",
      "Idea Prioritization",
      "Idea Archive",
      "Innovation Pipeline",
      "Research Initiatives",
      "Experiments & Spikes",
      "Community Suggestions",
      "Future Vision",
      "Related Documents"]),
]


# -------------------------------------------------------------------------
# ADR files (use the ADR_TEMPLATE, not the standard TEMPLATE)
# Each entry: (relative_path, number, title, description)
# -------------------------------------------------------------------------
ADR_FILES = [
    ("12_ADR/001_CONFIGURATION_DRIVEN_ARCHITECTURE.md",
     "001",
     "Configuration-Driven Architecture",
     "Decision to adopt a configuration-driven architecture where modules, workflows, forms, and rules are declaratively configured rather than hard-coded, enabling per-tenant customization without code changes."),

    ("12_ADR/002_MODULAR_ARCHITECTURE.md",
     "002",
     "Modular Architecture",
     "Decision to decompose the Ibn Hayan Healthcare Operating System into independent, well-bounded modules with explicit contracts, allowing each module to evolve, scale, and be enabled/disabled per tenant independently."),

    ("12_ADR/003_LOCAL_FIRST_STRATEGY.md",
     "003",
     "Local-First Strategy",
     "Decision to adopt a local-first data strategy where the system prefers local storage and synchronization over remote-first, ensuring functionality during network outages and reducing latency for clinics with poor connectivity."),

    ("12_ADR/004_MULTI_TENANT_STRATEGY.md",
     "004",
     "Multi-Tenant Strategy",
     "Decision to adopt a multi-tenant architecture with logical isolation (shared database, separate schemas/namespaces) for the SaaS deployment, balancing cost efficiency, performance, and data isolation requirements."),

    ("12_ADR/005_UI_DESIGN_PHILOSOPHY.md",
     "005",
     "UI Design Philosophy",
     "Decision to adopt a soft, refined, focused design philosophy inspired by best-in-class SaaS products (Linear, Stripe, Notion), with an 8px grid, restrained color palette, generous whitespace, and subtle motion."),

    ("12_ADR/006_DATABASE_STRATEGY.md",
     "006",
     "Database Strategy",
     "Decision to adopt a relational database (PostgreSQL) as the primary data store with JSONB for flexible schema extensions, supplemented by dedicated stores for files, search, and time-series data."),
]


def generate_file_content(title: str, description: str, sections: list) -> str:
    """Render a single markdown file from the standard TEMPLATE."""
    toc_lines = [f"{i}. {s}" for i, s in enumerate(sections, 1)]
    toc = "\n".join(toc_lines)
    section_blocks = [f"## {i}. {s}\n" for i, s in enumerate(sections, 1)]
    sections_md = "\n".join(section_blocks)
    return TEMPLATE.format(
        title=title,
        description=description,
        today=TODAY,
        toc=toc,
        sections=sections_md,
    )


def generate_adr_content(number: str, title: str, description: str) -> str:
    """Render a single ADR markdown file from the ADR_TEMPLATE."""
    return ADR_TEMPLATE.format(
        number=number,
        title=title,
        description=description,
        today=TODAY,
    )


def main() -> None:
    print("=" * 70)
    print("Ibn Hayan Healthcare Operating System — Documentation Generator v2")
    print("=" * 70)
    print(f"Output directory: {BASE}")
    print(f"Standard files to generate: {len(FILES)}")
    print(f"ADR files to generate: {len(ADR_FILES)}")
    print(f"Total files: {len(FILES) + len(ADR_FILES)}")
    print("-" * 70)

    # Step 1: Wipe existing docs/ tree (we regenerate from scratch)
    if BASE.exists():
        print("Removing existing docs/ tree...")
        shutil.rmtree(BASE)
    BASE.mkdir(parents=True, exist_ok=True)

    # Step 2: Generate standard documentation files
    print("\nGenerating standard documentation files...")
    created_standard = 0
    for rel_path, title, description, sections in FILES:
        full_path = BASE / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        content = generate_file_content(title, description, sections)
        full_path.write_text(content, encoding="utf-8")
        created_standard += 1
    print(f"  ✓ {created_standard} standard files created")

    # Step 3: Generate ADR files (different template)
    print("\nGenerating ADR files...")
    created_adr = 0
    for rel_path, number, title, description in ADR_FILES:
        full_path = BASE / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        content = generate_adr_content(number, title, description)
        full_path.write_text(content, encoding="utf-8")
        created_adr += 1
        print(f"  ✓ {rel_path}")
    print(f"  Total: {created_adr} ADR files created")

    # Step 4: Validation
    print("\n" + "=" * 70)
    print("VALIDATION REPORT")
    print("=" * 70)

    all_files = sorted(BASE.rglob("*.md"))
    all_folders = sorted({p.parent for p in all_files})

    top_level_folders = sorted({p.parts[0] for p in all_files if len(p.parts) > 1})
    subfolders = sorted({str(p.relative_to(BASE)) for p in all_folders if len(p.relative_to(BASE).parts) > 1})

    print(f"\nTotal top-level folders: {len(top_level_folders)}")
    for f in top_level_folders:
        print(f"  {f}")

    print(f"\nTotal subfolders: {len(subfolders)}")
    for s in subfolders:
        print(f"  {s}")

    print(f"\nTotal markdown files: {len(all_files)}")
    print(f"  Standard files: {created_standard}")
    print(f"  ADR files:      {created_adr}")

    # Check for sequential numbering (00-14)
    expected = [f"{i:02d}_" for i in range(15)]
    actual = [f for f in top_level_folders if f[:3] in [e[:3] for e in expected]]
    gaps = [e[:3] for e in expected if not any(f.startswith(e) for f in top_level_folders)]
    if gaps:
        print(f"\n⚠️  Numbering gaps detected: {gaps}")
    else:
        print(f"\n✅ Sequential numbering 00-14 verified (no gaps)")

    # Check no PROJECT_BIBLE references remain
    project_bible_refs = []
    for f in all_files:
        content = f.read_text(encoding="utf-8")
        if "PROJECT_BIBLE" in content:
            project_bible_refs.append(str(f))
    if project_bible_refs:
        print(f"\n⚠️  PROJECT_BIBLE references found in: {project_bible_refs}")
    else:
        print(f"✅ No PROJECT_BIBLE references found (PRODUCT_BIBLE is canonical)")

    # Verify ADR files use the ADR template (must contain "Decision", "Context", "Alternatives", "Consequences", "Status", "Future Notes")
    adr_validation_ok = True
    for rel_path, number, title, description in ADR_FILES:
        fpath = BASE / rel_path
        content = fpath.read_text(encoding="utf-8")
        required = ["## 1. Decision", "## 2. Context", "## 3. Alternatives", "## 4. Consequences", "## 5. Status", "## 6. Future Notes"]
        missing = [r for r in required if r not in content]
        if missing:
            print(f"⚠️  ADR {number} missing sections: {missing}")
            adr_validation_ok = False
    if adr_validation_ok:
        print(f"✅ All {len(ADR_FILES)} ADR files use the ADR template correctly")

    # Verify all standard files have the required structure
    standard_validation_ok = True
    for rel_path, title, description, sections in FILES:
        fpath = BASE / rel_path
        content = fpath.read_text(encoding="utf-8")
        if "Document Purpose:" not in content:
            print(f"⚠️  {rel_path} missing Document Purpose")
            standard_validation_ok = False
            continue
        if "## Table of Contents" not in content:
            print(f"⚠️  {rel_path} missing Table of Contents")
            standard_validation_ok = False
            continue
        for s in sections:
            if f"## {sections.index(s) + 1}. {s}" not in content:
                print(f"⚠️  {rel_path} missing section: {s}")
                standard_validation_ok = False
                break
    if standard_validation_ok:
        print(f"✅ All {len(FILES)} standard files have proper structure")

    print("\n" + "=" * 70)
    print("Documentation architecture upgrade COMPLETE.")
    print("=" * 70)


if __name__ == "__main__":
    main()
